name: kst_survey
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  date_time_picker: ^2.0.0
  grouped_buttons: ^1.0.4
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.1.3
  image_picker: ^0.7.4
  firebase_storage: ^8.0.5
  file_picker: ^3.0.1
  uuid: 3.0.4
  universal_html: ^2.0.8
  syncfusion_flutter_pdfviewer: ^19.1.59-beta
  path_provider: ^2.0.1
  open_file: ^3.2.1
  pdf: ^3.3.0
  printing: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/fonts/
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: SaysetthaOT
       fonts:
         - asset: assets/fonts/saysettha_ot.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: NotoSansLao
       fonts:
         - asset: assets/fonts/NotoSansLao-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
